const results = [
    {siteName:"Wikipedia", url:"https://en.wikipedia.org/wiki/Reflection_nebula", title:"Reflection nebula - Wikipedia", description:"In astronomy, reflection nebula are clouds of interstellar dust which might reflect the light of a nearby star or stars. The energy from the nearby stars is ..."},
    {siteName:"COSMOS", url:"https://astronomy.swin.edu.au/cosmos/r/Reflection+Nebul", title:"Reflection Nebula | COSMOS", description:"A reflection nebula is created when light from a star is scattered or reflected off a neighbouring dust cloud. The scattered light is slightly polarised and ..."},
    {siteName:"NASA", url:"https://www.nasa.gov/multimedia/imagegallery/image_feature_701.html", title:"Reflection Nebula - NASA", description:"Like fog around a street lamp, a reflection nebula shines only because the light from an embedded source illuminates its dust; the nebula ..."},
    {siteName:"brittanica", url:"https://www.britannica.com/science/reflection-nebula", title:"reflection nebula | astronomy | Britannica", description:"reflection nebula, interstellar cloud that would normally be a dark nebula (or molecular cloud) but whose dust reflects the light from a nearby bright star ..."},
    {siteName:"sun.org", url:"https://www.sun.org/encyclopedia/reflection-nebula", title:"Reflection nebula - Sun.org", description:"A reflection nebula is a cloud of interstellar gas and dust that reflects the light from other stars. This happens in the surroundings of ..."},
    {siteName:"The Planets", url:"https://theplanets.org/nebula-facts/reflection-nebula-facts/", title:"Reflection Nebula Facts - The Planets - THEPlanets.Org", description:"A reflection nebula is a cloud of interstellar dust that reflects the light of a nearby star or stars. The energy from the nearby stars is not enough to ionize ..."},
    {siteName:"NASA Hubblestite", url:"https://hubblesite.org/contents/media/images/2000/10/952-Image.html", title:"Reflection Nebula NGC 1999 - Hubble Space Telescope", description:"NGC 1999 is an example of a reflection nebula. Like fog around a street lamp, a reflection nebula shines only because the light from an embedded source ..."},
    {siteName:"ESA Hubble", url:"https://esahubble.org/images/opo0010a/", title:"A reflection nebula in Orion - ESA/Hubble", description:"A reflection nebula in Orion ... Just weeks after NASA astronauts repaired the Hubble Space Telescope in December 1999, the Hubble Heritage Project snapped this ..."},
    {siteName:"Universe Today", url:"https://www.universetoday.com/153436/this-is-a-classic-example-of-a-reflection-nebula-where-the-reflected-light-from-young-hot-stars-illuminates-a-protostellar-cloud-of-gas-and-dust/", title:"This is a Classic Example of a Reflection Nebula, Where ...", description:"A nebula starts with a cloud of interstellar dust. There are many clouds of dust out there in space, but it's the proximity of a star that ..."},
    {siteName:"Cool Cosmos", url:"https://coolcosmos.ipac.caltech.edu/ask/226-What-is-a-reflection-nebula-", title:"What is a reflection nebula? - Cool Cosmos - Caltech", description:"A reflection nebula is a cloud of gas and dust which does not create its own light, but instead shines by reflecting the light from nearby stars."}
]
modules.exports= results;
